<?php
ini_set('memory_limit', '2G');
require_once 'config.php';
require_once 'functions.php';
require_once 'UserDataImporter.php';

/**
 * Our user data was generated by https://www.mockaroo.com/
 * 
 * https://www.mockaroo.com/d836b220/download?count=1000&key=c6d46ff0
 */
$file = 'external-datasets/customers.csv';

$importer = new UserDataImporter(getDbConnection(), $file);
$importer->import();